### ISSUE TITLE
For use within a controller?

### ISSUE THREAD

**Issue by smebberson** [tafax/angular-state-machine#9]
This looks like some neat code. I'm wanting to use an FSM to handle conditional UI. It's for a filter interface in which I only want to allow the filter button to be clicked when one of the filter parameters changes and when all of the filter parameters are valid. It's actually quite a complex little task.

This project looks like it might help. Although, from what I can gather this is to control an entire app? It's not suitable for just within a controller for example?

**Comment by tafax** [comment]
Hi @smebberson,
FSM is a generic state machine library, so you can use it for any purpose. Anyway, I think your task is not suitable for a state machine. Based on you wrote, you can address it using a simple logic in the controller by displaying the filter button with a conditional code in your HTML and making it dependent on a boolean value that you can set based on filter parameters or whatever. Maybe, a state machine is a too complex strategy in your case.

**Comment by geemang2000** [comment]
I too have a usecase where FSM would be useful in a per-controller basis. I have a controller that needs to manage a series of UI interactions with my server (each with multiple branches) in order to complete a unit of work. As the state changes the UI might reflect the current state or prompt the user to fix something. I'm currently implementing my own StateMachine with the $scope variables. This isn't very DRY, so this lead me to look for a FSM module I can use across many controllers.   Is it possible to have multiple instances of FSM?
